### ISSUE TITLE
Players' Wins and Lost

### ISSUE THREAD

**Issue by aurelisajuan** [DanielChvat/CIS-17B-Connect4Project#9]
How are the players' wins being stored? Is there functions for it, or is it included in the Game.h file? The reason is because the User class is going to need the number of players' wins and lost, and we'll display that on the leaderboard.

@brittanyhailee @AureliaSindhu @aethiu @boolNoah-true @DanielChvat @Computer-PsiPhi @msalib1

**Comment by boolNoah-true** [comment]
The win logic can be found in the game state.cpp file in the end state at the bottom. You can use that logic to increment the win count in the user class. As of right now it doesn't store wins it just determines which player is the winner

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Aurelisa Sindhunirmala ***@***.***>
Sent: Monday, March 25, 2024 8:14:59 PM
To: DanielChvat/CIS-17B-Connect4Project ***@***.***>
Cc: Scott, Noah ***@***.***>; Mention ***@***.***>
Subject: [DanielChvat/CIS-17B-Connect4Project] Players' Wins and Lost (Issue #9)


How are the players' wins being stored? Is there functions for it, or is it included in the Game.h file? The reason is because the User class is going to need the number of players' wins and lost, and we'll display that on the leaderboard.

@brittanyhailee<https://github.com/brittanyhailee> @AureliaSindhu<https://github.com/AureliaSindhu> @aethiu<https://github.com/aethiu> @boolNoah-true<https://github.com/boolNoah-true> @DanielChvat<https://github.com/DanielChvat> @Computer-PsiPhi<https://github.com/Computer-PsiPhi> @msalib1<https://github.com/msalib1>

**Comment by boolNoah-true** [comment]
I reviewed our current code rn. The turnstate is checking who won based on a checkWin function coming from the board class. The endstate identifies who the winner is based on their index (winIdx). As of right now there is no storage of wins or losses. 

I was thinking we could just keep the storage inside the user class and the user class just gets who won from the game states class and increments wins and losses that way. 

Or we have the player class handle that and store the wins so that the user class can just take it from player. 

I also know we've been talking about having the board class return a player instead of a chip. If we are able to implement that then the user class can get who one from the board class at that point.

**Comment by Computer-PsiPhi** [comment]
I thought this was something the game class would handle. @aurelisajuan

**Comment by Computer-PsiPhi** [comment]
@aurelisajuan From what I remember this was something that was going to be implemented in the game class but I don't think it has been done yet as @boolNoah-true stated above.

**Comment by boolNoah-true** [comment]
@Computer-PsiPhi Yeah there's a TODO I put in the win logic in the gamestates class saying to implement storing winning to users which at the time had not been started but I didn't know if we still wanted to go that route or not. 

If so then @aurelisajuan @brittanyhailee @AureliaSindhu won't have to worry about getting the wins and can just make a variable for wins in the user class and i can work on the code in the gamestates class to pass the win to that variable in the user. 

Just want to make sure this is the correct idea with @Computer-PsiPhi and @aethiu first

**Comment by aethiu** [comment]
Yeah, it's not implemented yet, but the Game will eventually have a way to get the winning Player then some other class handles updating user's stats.

Ideally, I think a Players should be associated with a User, then the Game class stores winning Player and raises an event once a game ends. The menu (or whatever class' responsibility we decide it is) can subscribe to that event and update the User's wins. That way User concerns stay separate from the Game and being event based should make it web friendlier.
